prod:
  image: vizzuality/gfw-urthecast-api${STAGING}
  ports:
    - "4200"
  env_file:
    - prod.env
  command: start
  restart: always
  log_driver: "syslog"
  log_opt:
    syslog-address: ${SYSLOG_ADDRESS}
    tag: gfw-urthecast-api${STAGING}
