prod:
  image: vizzuality/gfw-urthecast-api${STAGING}
  ports:
    - "4200"
  env_file:
    - prod.env
  command: start
  log_driver: "gelf"
  restart: always
  log_opt:
    gelf-address: ${GELF_ADDRESS}
