swagger: '2.0'
info:
  title: GFW Urthecast API
  description: Global Forest Watch - Urthecast API.
  version: "1.0.0"

schemes:
  - https
  - http

produces:
  - application/vnd.api+json

paths:
  /map-tiles/{renderer}/{z}/{x}/{y}:
    get:
      operationId: getTile
      produces:
        - image/png
      tags:
        - URTHECAST
      parameters:
        - name: renderer
          in: path
          description: Renderer
          required: true
          type: string
        - name: z
          in: path
          description: z
          required: true
          type: string
        - name: x
          in: path
          description: x
          required: true
          type: string
        - name: y
          in: path
          description: y
          required: true
          type: string
        - name: cloud_coverage_lte
          in: query
          description: Average percentage of cloud coverage throughout the entire scene; calculated from its cloud mask. Maximum value. Example 30
          required: false
          type: string
        - name: acquired_gte
          in: query
          description: UTC date and time of when the scene's center was captured by the sensor_platform. Minimun date. Example 2016-07-20
          required: false
          type: string
        - name: acquired_lte
          in: query
          description: UTC date and time of when the scene was tiled and made available in the Urthecast archive. Maximun date. Example 2016-07-20
          required: false
          type: string
        - name: sensor_platform
          in: query
          description: Identifies the sensor that was used to capture the scene. Example "landsat-8 theia deimos-1"
          required: false
          type: string
      responses:
        200:
          description: Tile Image
        404:
          description: Geostore not found
          schema:
            $ref: '#/definitions/Errors'
        500:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Errors'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Errors'
  /urthecast/archive/scenes:
    get:
      operationId: getScenes
      produces:
        - application/vnd.api+json
      tags:
        - URTHECAST
      parameters:
        - name: geometry_intersects
          in: query
          description: The geographic boundary of the scene. example POINT(<lng>+<lat>)
          required: false
          type: string
        - name: cloud_coverage_lte
          in: query
          description: Average percentage of cloud coverage throughout the entire scene; calculated from its cloud mask
          required: false
          type: string
        - name: tiled_lte
          in: query
          description: UTC date and time of when the scene was tiled and made available in the Urthecast archive. Example 2016-07-20
          required: false
          type: string
        - name: acquired_gte
          in: query
          description: UTC date and time of when the scene's center was captured by the sensor_platform. Minimun date. Example 2016-07-20
          required: false
          type: string
        - name: acquired_lte
          in: query
          description: UTC date and time of when the scene was tiled and made available in the Urthecast archive. Maximun date. Example 2016-07-20
          required: false
          type: string
        - name: sort
          in: query
          description: Sort. Example -acquired
          required: false
          type: string
        - name: sensor_platform
          in: query
          description: Identifies the sensor that was used to capture the scene. Example "landsat-8 theia deimos-1"
          required: false
          type: string
      responses:
        200:
          description: Results obtained
          schema:
            $ref: '#/definitions/URTHECASTAPI'
        404:
          description: Geostore not found
          schema:
            $ref: '#/definitions/Errors'
        500:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Errors'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Errors'

definitions:
  Errors:
    type: object
    description: Errors
    properties:
      errors:
        type: array
        items:
          $ref: '#/definitions/Error'

  Error:
    type: object
    properties:
      id:
        type: integer
        format: int32
        description: A unique identifier for this particular occurrence of the problem.
      links:
        type: object
        description: A links object
        properties:
          about:
            type: string
            description: A link that leads to further details about this particular occurrence of the problem.
      status:
        type: string
        description: The HTTP status code applicable to this problem, expressed as a string value
      code:
        type: string
        description: An application-specific error code, expressed as a string value
      title:
        type: string
        description: A short, human-readable summary of the problem that SHOULD NOT change from occurrence to occurrence of the problem, except for purposes of localization.
      detail:
        type: string
        description: A human-readable explanation specific to this occurrence of the problem. Like title, this field's value can be localized
      source:
        type: object
        description: An object containing references to the source of the error, optionally including any of the following members
        properties:
          pointer:
            type: string
            description: A JSON Pointer [RFC6901] to the associated entity in the request document
          parameter:
            type: string
            description: A string indicating which URI query parameter caused the error.
      meta:
        type: object
        description: A meta object containing non-standard meta-information about the error.
  URTHECASTAPI:
    type: object
    properties:
      data:
        properties:
          schema:
            $ref: '#/definitions/URTHECASTBody'
  URTHECASTBody:
    type: object
    properties:
      type:
        type: string
        description: Resource type
      id:
        type: string
        description: Resource id
      attributes:
        properties:
          schema:
            $ref: '#/definitions/URTHECASTModel'

  URTHECASTModel:
    type: object
    properties:
      acquired:
        type: string
        format: date
      average_scene_altitude:
        type: number
        format: float
      cloud_coverage:
        type: number
        format: float
      earth_sun_distance:
        type: number
        format: float
      geometry:
        type: object
        properties:
          type:
            type: string
          coordinates:
            type: array
            items:
              type: number
      id:
        type: string
      owner:
        type: string
      owner_scene_id:
        type: string
      platform:
        type: string
      processed:
        type: string
        format: date
      satellite_id:
        type: number
        format: float
      scene_area:
        type: number
        format: float
      season:
        type: string
      sensor_platform:
        type: string
      solar_time_of_day_acquired:
        type: string
        format: time
      sun_azimuth:
        type: number
        format: float
      sun_elevation:
        type: number
        format: float
      tiled:
        type: string
        format: date
